do not reinstall woodpecker, if woodpecker source is not changed.

diff --git a/zstackwoodpecker/zstack-woodpecker b/zstackwoodpecker/zstack-woodpecker
--- a/zstackwoodpecker/zstack-woodpecker
+++ b/zstackwoodpecker/zstack-woodpecker
@@ -61,12 +61,16 @@ woodpecker_root_dir=`git rev-parse --show-toplevel`
 
 if [ -d "${woodpecker_root_dir}/zstackwoodpecker" ]; then
     cd ${woodpecker_root_dir}/zstackwoodpecker &>/dev/null
-    bash ./install.sh &>/dev/null
+    git diff |grep '+++' >/dev/null 2>&1
     if [ $? -eq 0 ]; then
-        echo -e "Woodpecker is correctly installed. Test begins ... \n\n"
-    else
-        echo "Woodpecker installation failure. Please check ... exit ."
-        exit 1
+        echo "Woodpecker source is updated, will reinstall zstack-woodpecker... please don't use ctrl-c to terminate installation, until the installation is finished."
+        bash ./install.sh &>/dev/null
+        if [ $? -eq 0 ]; then
+            echo -e "Woodpecker is correctly installed. Test begins ... \n\n"
+        else
+            echo "Woodpecker installation failure. Please check ... exit ."
+            exit 1
+        fi
     fi
 else
     echo "Your test config is not in zstack-woodpecker folder. If you modify zstack-woodpecker, please make sure install.sh is correctly run."
